### ISSUE TITLE
About Dataset Release

### ISSUE THREAD

**Issue by cs329yangzhong** [melaniesubbiah/storysumm#1]
Dear authors,

Thank you for contributing this valuable resource. May I ask when do you plan to release the dataset?

**Comment by melaniesubbiah** [comment]
Thanks for your interest! The code and data will be up next week.

**Comment by cs329yangzhong** [comment]
hi any update on this?

**Comment by melaniesubbiah** [comment]
Uploaded now, thanks for your patience!
